### ISSUE TITLE
Per-project Vim bindings

### ISSUE THREAD

**Issue by acobster** [acobster/dotfiles#5]
`<c-p><c-p>` is pretty efficient for creating mappings on the fly, but it'd be even nicer to have custom bindings loaded on a per-project basis. For example, one project might map `,t` to `lando test` while another might map `,t` to `phpunit`.

## TODO

- [ ] Convert `vms` to a bin script, so that it can source arbitrary files
- [ ] Source `~/.vim/session/$filename.session.vim`; create it if it doesn't exist
- [ ] Create abstractions for adding new mappings quickly
